export const STICKER_CATEGORIES = {
  emoji: [
    { id: 'sparkle', label: '✨ Sparkle', emoji: '✨' },
    { id: 'heart', label: '❤️ Heart', emoji: '❤️' },
    { id: 'fire', label: '🔥 Fire', emoji: '🔥' },
    { id: 'star', label: '⭐ Star', emoji: '⭐' },
    { id: 'rainbow', label: '🌈 Rainbow', emoji: '🌈' },
    { id: 'crown', label: '👑 Crown', emoji: '👑' },
    { id: 'diamond', label: '💎 Diamond', emoji: '💎' },
    { id: 'trophy', label: '🏆 Trophy', emoji: '🏆' },
    { id: 'medal', label: '🥇 Medal', emoji: '🥇' },
    { id: 'rocket', label: '🚀 Rocket', emoji: '🚀' },
    { id: 'lightning', label: '⚡ Lightning', emoji: '⚡' },
    { id: 'sun', label: '☀️ Sun', emoji: '☀️' },
    { id: 'moon', label: '🌙 Moon', emoji: '🌙' },
    { id: 'cloud', label: '☁️ Cloud', emoji: '☁️' },
    { id: 'snowflake', label: '❄️ Snowflake', emoji: '❄️' },
    { id: 'flower', label: '🌸 Flower', emoji: '🌸' },
    { id: 'rose', label: '🌹 Rose', emoji: '🌹' },
    { id: 'tulip', label: '🌷 Tulip', emoji: '🌷' },
    { id: 'cherry', label: '🍒 Cherry', emoji: '🍒' },
    { id: 'strawberry', label: '🍓 Strawberry', emoji: '🍓' },
  ],
  faces: [
    { id: 'smile', label: '😊 Smile', emoji: '😊' },
    { id: 'laugh', label: '😂 Laugh', emoji: '😂' },
    { id: 'love', label: '😍 Love', emoji: '😍' },
    { id: 'cool', label: '😎 Cool', emoji: '😎' },
    { id: 'party', label: '🥳 Party', emoji: '🥳' },
    { id: 'wink', label: '😉 Wink', emoji: '😉' },
    { id: 'kiss', label: '😘 Kiss', emoji: '😘' },
    { id: 'star_eyes', label: '🤩 Star Eyes', emoji: '🤩' },
    { id: 'thinking', label: '🤔 Thinking', emoji: '🤔' },
    { id: 'peace', label: '✌️ Peace', emoji: '✌️' },
    { id: 'ok', label: '👌 OK', emoji: '👌' },
    { id: 'thumbs_up', label: '👍 Thumbs Up', emoji: '👍' },
    { id: 'clap', label: '👏 Clap', emoji: '👏' },
    { id: 'muscle', label: '💪 Muscle', emoji: '💪' },
    { id: 'pray', label: '🙏 Pray', emoji: '🙏' },
  ],
  symbols: [
    { id: 'check', label: '✅ Check', emoji: '✅' },
    { id: 'cross', label: '❌ Cross', emoji: '❌' },
    { id: 'warning', label: '⚠️ Warning', emoji: '⚠️' },
    { id: 'info', label: 'ℹ️ Info', emoji: 'ℹ️' },
    { id: 'question', label: '❓ Question', emoji: '❓' },
    { id: 'exclamation', label: '❗ Exclamation', emoji: '❗' },
    { id: 'recycle', label: '♻️ Recycle', emoji: '♻️' },
    { id: 'infinity', label: '♾️ Infinity', emoji: '♾️' },
    { id: 'copyright', label: '©️ Copyright', emoji: '©️' },
    { id: 'registered', label: '®️ Registered', emoji: '®️' },
    { id: 'tm', label: '™️ Trademark', emoji: '™️' },
    { id: 'new', label: '🆕 New', emoji: '🆕' },
    { id: 'free', label: '🆓 Free', emoji: '🆓' },
    { id: 'cool_icon', label: '🆒 Cool', emoji: '🆒' },
    { id: 'ok_icon', label: '🆗 OK', emoji: '🆗' },
  ],
  animals: [
    { id: 'dog', label: '🐶 Dog', emoji: '🐶' },
    { id: 'cat', label: '🐱 Cat', emoji: '🐱' },
    { id: 'rabbit', label: '🐰 Rabbit', emoji: '🐰' },
    { id: 'bear', label: '🐻 Bear', emoji: '🐻' },
    { id: 'panda', label: '🐼 Panda', emoji: '🐼' },
    { id: 'koala', label: '🐨 Koala', emoji: '🐨' },
    { id: 'tiger', label: '🐯 Tiger', emoji: '🐯' },
    { id: 'lion', label: '🦁 Lion', emoji: '🦁' },
    { id: 'cow', label: '🐮 Cow', emoji: '🐮' },
    { id: 'pig', label: '🐷 Pig', emoji: '🐷' },
    { id: 'frog', label: '🐸 Frog', emoji: '🐸' },
    { id: 'monkey', label: '🐵 Monkey', emoji: '🐵' },
    { id: 'chicken', label: '🐥 Chicken', emoji: '🐥' },
    { id: 'penguin', label: '🐧 Penguin', emoji: '🐧' },
    { id: 'bird', label: '🐦 Bird', emoji: '🐦' },
  ],
  food: [
    { id: 'pizza', label: '🍕 Pizza', emoji: '🍕' },
    { id: 'burger', label: '🍔 Burger', emoji: '🍔' },
    { id: 'fries', label: '🍟 Fries', emoji: '🍟' },
    { id: 'hotdog', label: '🌭 Hotdog', emoji: '🌭' },
    { id: 'taco', label: '🌮 Taco', emoji: '🌮' },
    { id: 'sushi', label: '🍣 Sushi', emoji: '🍣' },
    { id: 'ramen', label: '🍜 Ramen', emoji: '🍜' },
    { id: 'coffee', label: '☕ Coffee', emoji: '☕' },
    { id: 'beer', label: '🍺 Beer', emoji: '🍺' },
    { id: 'wine', label: '🍷 Wine', emoji: '🍷' },
    { id: 'cocktail', label: '🍹 Cocktail', emoji: '🍹' },
    { id: 'cake', label: '🎂 Cake', emoji: '🎂' },
    { id: 'cookie', label: '🍪 Cookie', emoji: '🍪' },
    { id: 'donut', label: '🍩 Donut', emoji: '🍩' },
    { id: 'ice_cream', label: '🍦 Ice Cream', emoji: '🍦' },
  ],
  activities: [
    { id: 'soccer', label: '⚽ Soccer', emoji: '⚽' },
    { id: 'basketball', label: '🏀 Basketball', emoji: '🏀' },
    { id: 'football', label: '🏈 Football', emoji: '🏈' },
    { id: 'baseball', label: '⚾ Baseball', emoji: '⚾' },
    { id: 'tennis', label: '🎾 Tennis', emoji: '🎾' },
    { id: 'volleyball', label: '🏐 Volleyball', emoji: '🏐' },
    { id: 'bowling', label: '🎳 Bowling', emoji: '🎳' },
    { id: 'golf', label: '⛳ Golf', emoji: '⛳' },
    { id: 'guitar', label: '🎸 Guitar', emoji: '🎸' },
    { id: 'microphone', label: '🎤 Microphone', emoji: '🎤' },
    { id: 'camera', label: '📷 Camera', emoji: '📷' },
    { id: 'movie', label: '🎬 Movie', emoji: '🎬' },
    { id: 'game', label: '🎮 Game', emoji: '🎮' },
    { id: 'dice', label: '🎲 Dice', emoji: '🎲' },
    { id: 'target', label: '🎯 Target', emoji: '🎯' },
  ]
};

export const GOOGLE_FONTS = [
  'Roboto', 'Open Sans', 'Lato', 'Montserrat', 'Oswald',
  'Source Sans Pro', 'Raleway', 'PT Sans', 'Merriweather', 'Ubuntu',
  'Playfair Display', 'Poppins', 'Noto Sans', 'Mukta', 'Work Sans',
  'Rubik', 'Inter', 'Nunito', 'Nunito Sans', 'Quicksand',
  'Fira Sans', 'Oxygen', 'Karla', 'Cabin', 'Barlow',
  'Josefin Sans', 'Crimson Text', 'Inconsolata', 'Dancing Script', 'Pacifico',
  'Lobster', 'Bebas Neue', 'Anton', 'Righteous', 'Archivo',
  'Arimo', 'Exo 2', 'Comfortaa', 'Abel', 'Varela Round',
  'Shadows Into Light', 'Satisfy', 'Amatic SC', 'Caveat', 'Indie Flower',
  'Permanent Marker', 'Zilla Slab', 'Bitter', 'IBM Plex Sans', 'Noto Serif',
  'Titillium Web', 'Assistant', 'Heebo', 'Libre Franklin', 'Signika',
  'Alegreya Sans', 'Yanone Kaffeesatz', 'Pathway Gothic One', 'Architects Daughter', 'Courgette',
  'Great Vibes', 'Orbitron', 'Sacramento', 'Bangers', 'Press Start 2P',
  'Bree Serif', 'Alfa Slab One', 'Play', 'Acme', 'Teko',
  'Russo One', 'Fjalla One', 'Abril Fatface', 'Cinzel', 'Kaushan Script',
  'Spectral', 'Cormorant Garamond', 'EB Garamond', 'Libre Baskerville', 'Rokkitt',
  'Hind', 'PT Serif', 'Vollkorn', 'Domine', 'Crete Round',
  'Archivo Narrow', 'Muli', 'Asap', 'Cantarell', 'Dosis',
  'Questrial', 'Maven Pro', 'Chivo', 'Source Code Pro', 'Space Mono',
  'Catamaran', 'Slabo 27px', 'Patua One', 'Fredoka One', 'Yellowtail'
];
